/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package assignment;


import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.sql.*;

/**
 *
 * @author R E V O
 */
public class Manage_Users extends javax.swing.JFrame {

Admin objd = new Admin();
    public Manage_Users() {
        
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jFName = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLName = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jusertype = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txt_Username2 = new javax.swing.JTextField();
        txt_Newpass = new javax.swing.JPasswordField();
        txt_ConfirmPass = new javax.swing.JPasswordField();
        btn_Search = new javax.swing.JButton();
        btn_Passchange = new javax.swing.JButton();
        btn_UserChange = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        txt_Username1 = new javax.swing.JTextField();
        btn_back = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jFName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jFName);
        jFName.setBounds(640, 160, 270, 16);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel4.setText("First Name:");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(530, 160, 100, 22);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("Last Name:");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(530, 210, 100, 22);

        jLName.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jLName);
        jLName.setBounds(640, 220, 200, 16);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("New Password");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(40, 250, 140, 22);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("Usertype:");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(530, 110, 100, 22);

        jusertype.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(jusertype);
        jusertype.setBounds(640, 110, 200, 16);

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("Manage Users");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 10, 250, 60);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("Confirm Password");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(40, 330, 150, 22);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel11.setText("Username");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(40, 170, 77, 22);
        jPanel1.add(txt_Username2);
        txt_Username2.setBounds(200, 160, 190, 40);

        txt_Newpass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt_Newpass);
        txt_Newpass.setBounds(200, 250, 180, 50);

        txt_ConfirmPass.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jPanel1.add(txt_ConfirmPass);
        txt_ConfirmPass.setBounds(200, 320, 180, 50);

        btn_Search.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btn_Search.setText("Search User");
        btn_Search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SearchActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Search);
        btn_Search.setBounds(370, 380, 180, 60);

        btn_Passchange.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_Passchange.setText("Change");
        btn_Passchange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_PasschangeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_Passchange);
        btn_Passchange.setBounds(400, 330, 90, 25);

        btn_UserChange.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        btn_UserChange.setText("Change");
        btn_UserChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UserChangeActionPerformed(evt);
            }
        });
        jPanel1.add(btn_UserChange);
        btn_UserChange.setBounds(400, 170, 100, 25);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel12.setText("Username");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(40, 100, 77, 22);

        txt_Username1.setText("Type here to search");
        jPanel1.add(txt_Username1);
        txt_Username1.setBounds(200, 90, 190, 40);

        btn_back.setIcon(new javax.swing.ImageIcon("C:\\Others\\ICBT Assigments\\ICBT Assignemnt 6\\Assignment\\icons\\arrow-back-icon (1).png")); // NOI18N
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        jPanel1.add(btn_back);
        btn_back.setBounds(20, 20, 20, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Others\\ICBT Assigments\\ICBT Assignemnt 6\\Assignment\\Pics\\JnFefL.jpg")); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 860, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 861, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 461, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(879, 508));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SearchActionPerformed
      try  
      {
          objd.setUsername(txt_Username1.getText());
        ResultSet rs=objd.SearchUser();
          
          
          
          if (rs.next())
          {
          jusertype.setText(rs.getString("Usertype"));
          jFName.setText(rs.getString("First_Name"));
          jLName.setText(rs.getString("Last_Name"));
          JOptionPane.showMessageDialog(null, "User found");
          }else{
          JOptionPane.showMessageDialog(null, "User not found");
          }
         
          }
      catch (Exception ex)
       {
           JOptionPane.showMessageDialog(null,"Error searchinig data"+ex);
       } 
    }//GEN-LAST:event_btn_SearchActionPerformed

    private void btn_UserChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UserChangeActionPerformed
        try{
            
        objd.setUsername(txt_Username2.getText());
        int Norows=objd.Updates(txt_Username1.getText());
    if(Norows>0) 
    {
        JOptionPane.showMessageDialog(null, "Username Changed");
    }
    else{
    JOptionPane.showMessageDialog(null,"Check Details to be updated");
    }
 }

    catch (Exception ex)
           {
             JOptionPane.showMessageDialog(null, "Error updating data"+ex);   
                }
    }//GEN-LAST:event_btn_UserChangeActionPerformed

    private void btn_PasschangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_PasschangeActionPerformed
        String New_Pass = txt_Newpass.getText().toString();
         String Confirm_Pass = txt_ConfirmPass.getText().toString();
         
        boolean valid = objd.validatePass(New_Pass, Confirm_Pass);
        if (valid){
           objd.setPassword(txt_ConfirmPass.getText());
           objd.setUsername(txt_Username1.getText());
        objd.Updates();
        JOptionPane.showMessageDialog(null, "Password changed");
        }
         
    }//GEN-LAST:event_btn_PasschangeActionPerformed

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed
        dispose();
        Main_Interface op = new Main_Interface();
        op.setVisible(true);
        op.btn_Register.setEnabled(false);
        op.btn_update.setEnabled(false);
        op.btn_Generate.setEnabled(false);
    }//GEN-LAST:event_btn_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manage_Users.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Manage_Users().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Passchange;
    private javax.swing.JButton btn_Search;
    private javax.swing.JButton btn_UserChange;
    private javax.swing.JButton btn_back;
    private javax.swing.JLabel jFName;
    private javax.swing.JLabel jLName;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jusertype;
    private javax.swing.JPasswordField txt_ConfirmPass;
    private javax.swing.JPasswordField txt_Newpass;
    private javax.swing.JTextField txt_Username1;
    private javax.swing.JTextField txt_Username2;
    // End of variables declaration//GEN-END:variables
}
